### PR TITLE
Noting that some converters are broken.

### PR DESCRIPTION
**Pull request by peterb12**
As in title.

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks for this @peterb12. It's useful information. But I think in that form, and maintained manually, it will be too random (applied to some links and not others), too subjective/lacking in detail ("not working"), and too hard to maintain. How committed are you to maintaining such information ? Any ideas on other ways to manage it ?

**Comment by peterb12** [comment]
I'm not particularly committed to maintaining it.

Honestly I think the **right** thing to do is to remove any item from the list that doesn't work as reports come in that they're broken, and then they can be added back in if the maintainers ever get around to updating their tools. Right now this gives the impression that there are hundreds of actively-maintained tools, whereas the reality is that many of the items on that list are long-abandoned gists, with tumbleweeds rolling by.

**Comment by simonmichael** [comment]
I'm in sympathy with that. Until now all links are included as even dormant projects can be useful to someone. I agree it would be great to have some kind of scalable-enough, maintainable-enough way to indicate such status for all linked software, not just the main ledger-likes. Another way would be to show last-tested dates, some kind of badge, or separate active and inactive lists. It would help to document some standard criteria that anyone could apply. Can you think of some ? 

It would be easier if this was a more dynamic list/database, with voting etc.

**Comment by simonmichael** [comment]
At minimum we could add some text at the top, and perhaps in each section, to set expectations.

**Comment by tbm** [comment]
fwiw, the background of this is: https://www.reddit.com/r/plaintextaccounting/comments/exv5o8/ledger_to_beancount_up_to_date_tools/fgfex4u/

While I'm not sure about listing what's broken, I agree that the current list is too big and includes a lot of stuff that isn't really useful. Maybe it would make sense to split the section, but I'm not entirely sure how.

**Comment by simonmichael** [comment]
One easyish thing we could do is add the year of last update to all links ?

**Comment by simonmichael** [comment]
We still a scalable way to make our links more useful. @peterb12 I tried adding these notes, but they create too much ongoing maintenance - we can reopen this PR if anyone has new ideas.

**Pull request closed without merging**
