### PR TITLE
Modify formatting of questions.

### PR DESCRIPTION
**Pull request by mwfogleman**

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks! I don't find that style (no space before question mark) natural. Feel free to cite any style guides which might change my mind.

**Comment by mwfogleman** [comment]
There is an interesting discussion of this here:
https://english.stackexchange.com/questions/4645/is-it-ever-correct-to-have-a-space-before-a-question-or-exclamation-mark

You can also look at the examples in this style guide:
http://www.thepunctuationguide.com/terminal-points.html

**Comment by simonmichael** [comment]
Also https://simple.wikipedia.org/wiki/Question_mark. Ugh, I don't like it but ok let's try :) Thanks.

**Comment by simonmichael** [comment]
PS I think there might be a few more cases still to fix.

**Pull request merged**
