### PR TITLE
reorganize data import / conversion sections

### PR DESCRIPTION
**Pull request by zacchiro**
in particular:

- split data import (to get your transactions in your ledger from your bank)
  and data converters (to convert between different ledger systems)

- sort alphabetically tools within each section

- organize converters in sub-lists depending on the use case

- ledger to beancount: add a missing tool, try to provide oneliner descriptions
  to differentiate the options

### CODE REVIEW

**Comment by zacchiro** [comment]
I couldn't get the build toolchain to work on my laptop (pandoc failed even on current master), so this PR includes only changes to `index.md`. I hope this is fine :-)

**Comment by simonmichael** [comment]
Thanks!

What's the pandoc problem ? Did you get it installed ?

The problem with splitting importers and converters is there's a lot of overlap. Are you sure you want to do that ? 

Lots of converters still listed under data import.

dumbs -> dumps

The table of contents ("read more" at top right) needs updating.

**Comment by zacchiro** [comment]
On Thu, Apr 19, 2018 at 04:26:03PM +0000, Simon Michael wrote:
> What's the pandoc problem ? Did you get it installed ?

Yeah, and I also use pandoc regularly without issues. But when I do make
in the website repo I get this:

```
$ make
pandoc -f markdown-smart+autolink_bare_uris --template index.tmpl CONTRIBUTING.md -o CONTRIBUTING.html
pandoc: Unknown extension: smart
Makefile:10: recipe for target 'CONTRIBUTING.html' failed
make: *** [CONTRIBUTING.html] Error 7
```

> The problem with splitting importers and converters is there's a lot
> of overlap. Are you sure you want to do that ?

So, my take is that there is a clear rationale here: tools you use to
get transaction *in* your accounting systems (which sometimes read CSV,
sometime use your bank API, but either way they still serve that
purpose) v. tools to convert *between* accounting systems.

I think that's a clear cut distinction. YMMV.

> Lots of converters still listed under data import.

That said, I don't know all of the tools, so it is possible I
miscategorized some of them.

> dumbs -> dumps
>
> The table of contents ("read more" at top right) needs updating.

Nice catch. Both fixed now.

**Comment by simonmichael** [comment]
I think you may need a newer pandoc. What version have you ?

**Comment by simonmichael** [comment]
I don't see that the distinction is clear enough, for users or editors, yet. Eg as a user, your "data import" looks like a list of "converters":

    Ledger in Go has limport, a CSV to *ledger converter
    Ledger and hledger have CSV conversion built in
    banks2ledger - CSV to *ledger converter
    beancount-import CSV to beancount converter (curses)
    csv2beancount CSV to beancount converter
    hledger-import-dsl alternate, programmable CSV converter for hledger
    icsvledger CSV to *ledger converter
    into-ledger CSV to *ledger converter
    ledger-autosync OFX download, OFX to *ledger conversion, deduplication
    ledger-get-prices download market prices
    ledger-reconciler automatically download and reconcile your ledger financial entries
    ledgerbil schedule recurring txns, interactive reconcile, date sorting
    plaid2qif Download transactions from plaid as QIF or CSV files
    plaid2text Plaid API to *ledger/beancount download/conversion
    reckon smart interactive/non-interactive CSV to *ledger converter
    smart_importer library for building smarter CSV to beancount/Fava converters
    total_recall CSV to *ledger converter
    bean-identify, bean-extract, bean-file - Beancount built-in tools

And "data conversion" looks like a different list of converters:

    from You Need a Budget:
        beancount-ynab You Need A Budget to beancount converter
        ynab_to_ledger You Need A Budget to *ledger converter
    from Grisbi: grisbi2Ledger Grisbi to *ledger converter
    from Gnucash:
        gnucash-to-beancount GnuCash to beancount converter
        gnucash2ledger.py GNUCash to *ledger converter
    from Quickbooks:
        qb2ledger QuickBooks General Journal CSV to *ledger converter
        outofit QuickBooks to *ledger converter
    from QIF: QIFtoLedger (Bank of America's) QIF to *ledger converter
    from Ledger to Beancount:
        ledger-to-beancount another Ledger to Beancount converter
        ledger2beancount.py *ledger to beancount converter
        ledger2beancount feature complete ledger to beancount syntactic converter

(I like the "from X" categorisation.)

As an editor, I'm not sure where I'd place things, which adds friction. ledger-autosync is one example of a tool that crosses categories - it does fetch, convert, and/or deduplicate; possibly import as well. I'm sure there are more examples. It's quite a lot of work to find out exactly what each of these tools does.

**Comment by simonmichael** [comment]
PS I've enabled the wiki, in case you want an easier place to preview changes; there's also the http://scratch.hledger.org etherpad.

**Comment by zacchiro** [comment]
> I don't see that the distinction is clear enough, for users or editors, yet. Eg as a user, your "data import" looks like a list of "converters":

I disagree. They "convert" from native export formats from banks or related APIs, *not* from other accounting systems where you've already ingested your bank data. That is a key conceptual distinction at the work-flow level for me.

But, again, YMMV. This was a suggestion. If you disagree, that's fine, just close this PR :-)

**Comment by simonmichael** [comment]
I'm simply going by the wording - they mostly say "converter". The distinction that you're seeing isn't clear to me as a user (or, distracted editor). I think at least it needs more work to make that clearer, otherwise I'm going to have a hard time maintaining this. If you'd like to take on that responsibility, then I'm ok with it!

**Comment by simonmichael** [comment]
Sorry not to get your changes in. If you're out of time for this, I understand. I'll make a few more notes. To successfully break up this category, we should probably define some concepts better. Till now I've been thinking in these terms:

- fetching: downloading data from a remote source. Eg CSV or OFX files from a bank's UI, OFX data from a bank's OFX/Direct API, market prices from the net.
- converting: reading one kind of data and writing another. Eg: CSV to ledger, OFX to beancount, ledger to beancount.
- importing: merging new data into your main data files. Eg adding transactions to the journal, or prices to a prices file. 
- deduplication: detecting and discarding data processed previously. Can be done during any of the above steps.

And I think you are distinguishing:

- raw/bank/api data (CSV, OFX..) vs rich/accounting data (h/ledger, beancount, gnucash..)
- converting from raw to rich formats vs converting between rich formats

**Pull request closed without merging**
